/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./public/**/*.{html,js}",
    "./views/**/*.{html,js}",
    "./pages/**/*.{html,js}",
    "./*.html",
    "./js/**/*.js",
    "./src/**/*.js",
  ],
  darkMode: 'class', // Enable class-based dark mode
  theme: {
    extend: {
      colors: {
        // Maktoub Brand Colors - Now using CSS variables for theming
        maktoub: {
          dark: 'var(--bg-primary)',
          primary: 'var(--color-primary)',
          main: 'var(--color-primary)', // Alias for primary
          light: 'var(--text-secondary)',
          white: 'var(--text-primary)',
          med: '#066458',
          accent: '#A7F44A',
          teal: {
            50: '#F1FCFA',
            100: '#CFF8EE',
            200: '#9FF0DE',
            300: '#67E1CB',
            400: '#38C9B4',
            500: 'var(--color-primary)',
            600: '#168B7F',
            700: '#166F66',
            800: '#165954',
            900: '#174A46',
            950: '#072C2A',
          },
        },
        // Gray Scale
        gray: {
          50: '#F9FAFB',
          100: '#F3F4F6',
          200: '#E5E7EB',
          300: '#D1D5DB',
          400: '#9CA3AF',
          500: '#6B7280',
          600: '#4B5563',
          700: '#374151',
          800: '#1F2937',
          900: '#111827',
        },
        // Utility Colors
        white: '#FFFFFF',
        black: '#000000',
      },
      fontFamily: {
        'janna': ['Janna LT', 'Tajawal', 'Arial', 'sans-serif'],
        'inter': ['Inter', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        'arabic': ['Janna LT', 'Tajawal', 'Arial', 'sans-serif'],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '16px' }],
        'sm': ['14px', { lineHeight: '20px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '28px' }],
        'xl': ['20px', { lineHeight: '28px' }],
        '2xl': ['24px', { lineHeight: '32px' }],
        '3xl': ['30px', { lineHeight: '36px' }],
        '4xl': ['36px', { lineHeight: '40px' }],
        '5xl': ['48px', { lineHeight: '1' }],
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '9': '36px',
        '10': '40px',
        '11': '44px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
      },
      borderRadius: {
        'none': '0',
        'sm': '4px',
        DEFAULT: '6px',
        'md': '6px',
        'lg': '8px',
        'xl': '12px',
        '2xl': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'sm': '0px 1px 2px rgba(0, 0, 0, 0.05)',
        DEFAULT: '0px 1px 3px rgba(0, 0, 0, 0.1), 0px 1px 2px rgba(0, 0, 0, 0.06)',
        'md': '0px 4px 6px -1px rgba(0, 0, 0, 0.1), 0px 2px 4px -1px rgba(0, 0, 0, 0.06)',
        'lg': '0px 10px 15px -3px rgba(0, 0, 0, 0.1), 0px 4px 6px -2px rgba(0, 0, 0, 0.05)',
        'xl': '0px 20px 25px -5px rgba(0, 0, 0, 0.1), 0px 10px 10px -5px rgba(0, 0, 0, 0.04)',
        'none': 'none',
      },
      backgroundImage: {
        'hero-dark': "url('/attached_assets/ Images & Graphics/Hero background/Dark Mode/SVG/Hero_Background_1.svg')",
        'hero-light': "url('/attached_assets/ Images & Graphics/Hero background/Light Mode/SVG/Hero_Background_L.svg')",
      },
      opacity: {
        '0': '0',
        '30': '0.3',
        '50': '0.5',
        '70': '0.7',
        '90': '0.9',
        '100': '1',
      },
    },
  },
  plugins: [],
}
